# Hub agent deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-hub-agent
  namespace: 62ccf81a9d3e68000159b903
  labels:
    app.kubernetes.io/name: fleet-hub-agent
    app.kubernetes.io/version: "0.1.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fleet-hub-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fleet-hub-agent
    spec:
      containers:
        - name: hub-agent
          image: "testfleetagent.azurecr.io/hub-agent:v0.1.0"
          args:
            - --kubeconfig=/etc/kubernetes/kubeconfig/kubeconfig.yaml
            - --v=5
          volumeMounts:
            - mountPath: /etc/kubernetes/kubeconfig
              readOnly: true
              name: kubeconfig
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig-file