---
# Source: fleet-agent/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-agent-sa
  namespace: 62ccf8009d3e68000159b902
  labels:
    helm.sh/chart: fleet-agent-0.1.0
    app.kubernetes.io/name: fleet-agent
    app.kubernetes.io/instance: fleet-agent
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: fleet-agent/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: 62ccf8009d3e68000159b902
rules:
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "get", "list", "watch", "create", "patch" ]
  
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "" ]
    resources: ["nodes"]
    verbs: [ "get", "list", "watch"]
---
# Source: fleet-agent/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 62ccf8009d3e68000159b902
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 62ccf8009d3e68000159b902
subjects:
  - kind: ServiceAccount
    name: fleet-agent-sa
    namespace: 62ccf8009d3e68000159b902
---
# Source: fleet-agent/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-agent
  namespace: 62ccf8009d3e68000159b902
  labels:
    helm.sh/chart: fleet-agent-0.1.0
    app.kubernetes.io/name: fleet-agent
    app.kubernetes.io/instance: fleet-agent
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fleet-agent
      app.kubernetes.io/instance: fleet-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fleet-agent
        app.kubernetes.io/instance: fleet-agent
    spec:
      serviceAccountName: fleet-agent-sa
      containers:
        
        - name: msi-adapter
          image: mcr.microsoft.com/aks/ccp/msi-adapter:master.220529.1
          imagePullPolicy: IfNotPresent
          env:
            - name: SUBSCRIPTION_ID
              value: 8ecadfc9-d1a3-4ea4-b844-0d9f87e4d7c8
            - name: RESOURCE_GROUP_NAME
              value: liqianluebld57534826
            - name: MANAGED_CLUSTER_NAME
              value: member1
            - name: CONTROL_PLANE_ID
              value: 62ccf8009d3e68000159b902
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
        
        - name: fleet-agent
          image: "testfleetagent.azurecr.io/member-agent:v0.1.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          args:
            - --tls-insecure=true
            - --v=5
          env:
            - name: HUB_SERVER_URL
              value: "https://hub-f695e944.hcp.liqianluebld57534826.e2e.azmk8s.io:443"
            - name: CONFIG_PATH
              value: "/config/token"
            - name: MEMBER_CLUSTER_NAME
              value: "member1"
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: provider-token
              mountPath: /config

        - name: refresh-token
          image: "testfleetagent.azurecr.io/refresh-token:v0.1.0"
          imagePullPolicy: Always
          args:
            - azure
            - --clientid=d58772ec-ff68-444e-8c29-386ecdacea19
            - --v=5
            
          ports:
            - name: http
              containerPort: 4000
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
          - name: provider-token
            mountPath: /config

      
      volumes:
      - name: provider-token
        emptyDir: { }
