# Member agent deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-member-agent
  namespace: 62ccf8009d3e68000159b902
  labels:
    app.kubernetes.io/name: fleet-member-agent
    app.kubernetes.io/version: "0.1.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fleet-member-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fleet-member-agent
    spec:
      containers:
        - name: msi-adapter
          image: mcr.microsoft.com/aks/ccp/msi-adapter:master.220529.1
          env:
            - name: SUBSCRIPTION_ID
              value: 8ecadfc9-d1a3-4ea4-b844-0d9f87e4d7c8
            - name: RESOURCE_GROUP_NAME
              value: liqianluebld57534826
            - name: MANAGED_CLUSTER_NAME
              value: member1
            - name: CONTROL_PLANE_ID
              value: 62ccf8009d3e68000159b902
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
        - name: refresh-token
          image: "testfleetagent.azurecr.io/refresh-token:v0.1.0"
          args:
            - azure
            - --clientid=d58772ec-ff68-444e-8c29-386ecdacea19
            - --v=5
          ports:
            - name: http
              containerPort: 4000
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: provider-token
              mountPath: /config
        - name: member-agent
          image: "testfleetagent.azurecr.io/member-agent:v0.1.0"
          args:
            - --kubeconfig=/etc/kubernetes/kubeconfig/kubeconfig.yaml
            - --tls-insecure=true
            - --v=5
          env:
            - name: HUB_SERVER_URL
              value: "https://hub-f695e944.hcp.liqianluebld57534826.e2e.azmk8s.io:443"
            - name: CONFIG_PATH
              value: "/config/token"
            - name: MEMBER_CLUSTER_NAME
              value: "member1"
          volumeMounts:
            - mountPath: /etc/kubernetes/kubeconfig
              readOnly: true
              name: kubeconfig
            - name: provider-token
              mountPath: /config
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
      - name: provider-token
        emptyDir: { }
      - name: kubeconfig
        secret:
          secretName: kubeconfig-file
