apiVersion: v1
kind: Service
metadata:
  name: kuar-dummy
  labels:
    app: kuar
spec:
  type: LoadBalancer
  ports:
    - port: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kuar-dummy
subsets:
  - addresses:
      - ip: 10.0.1.6
      - ip: 10.0.2.11
      - ip: 10.3.4.21
    ports:
      - port: 8080